import type {
  GetServerSideProps,
  GetServerSidePropsContext,
  NextPage,
} from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage<{ slug: string; gitRef: string }> = ({ slug, gitRef }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <p>GIT REF {gitRef}</p>
        <p>SLUG {slug}</p>
      </main>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async function (
  ctx: GetServerSidePropsContext
) {
  const GIT_REF = process.env.NEXT_PUBLIC_GIT_COMMIT_REF;
  const SLUG = process.env.NEXT_PUBLIC_VERCEL_GIT_REPO_SLUG;

  return {
    props: {
      gitRef: GIT_REF,
      slug: SLUG,
    },
  };
};

export default Home;
